# Generated by Django 4.2.4 on 2023-08-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="publishDate",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date published"
            ),
        ),
    ]
