# Generated by Django 4.2.4 on 2023-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ProductImage",
            field=models.ImageField(null=True, upload_to="./images/"),
        ),
    ]
