# Generated by Django 4.2.4 on 2023-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_product_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ProductImage",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
