# Generated by Django 4.2.4 on 2023-08-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_smalllinkannouncement"),
    ]

    operations = [
        migrations.AddField(
            model_name="smalllinkannouncement",
            name="ProductImage",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
