# Generated by Django 4.2.4 on 2023-08-03 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_smalllinkannouncement_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="smalllinkannouncement",
            old_name="ProductImage",
            new_name="AnnounceImage",
        ),
    ]
