# Generated by Django 4.2.4 on 2023-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_rename_productimage_smalllinkannouncement_announceimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smalllinkannouncement",
            name="description",
        ),
        migrations.AddField(
            model_name="smalllinkannouncement",
            name="SeeMoreLink",
            field=models.TextField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
