# Generated by Django 4.2.4 on 2023-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0011_remove_smalllinkannouncement_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smalllinkannouncement",
            name="SeeMoreLink",
            field=models.URLField(max_length=250),
        ),
    ]
