# Generated by Django 4.2.4 on 2023-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0012_alter_smalllinkannouncement_seemorelink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="ProductImage",
            new_name="PicSrc",
        ),
        migrations.AlterField(
            model_name="smalllinkannouncement",
            name="SeeMoreLink",
            field=models.URLField(max_length=250, null=True),
        ),
    ]
