# Generated by Django 4.2.4 on 2023-08-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0014_alter_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="publishDate",
            field=models.DateTimeField(null=True, verbose_name="date published"),
        ),
    ]
