# Generated by Django 4.2.4 on 2023-08-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0016_alter_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picSrc", models.ImageField(upload_to="images")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=100)),
            ],
        ),
    ]
