# Generated by Django 4.2.4 on 2023-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0017_slider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slider",
            old_name="picSrc",
            new_name="picSrc1",
        ),
        migrations.AddField(
            model_name="slider",
            name="picSrc2",
            field=models.ImageField(default="", upload_to="images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="picSrc3",
            field=models.ImageField(default="", upload_to="images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="picSrc4",
            field=models.ImageField(default="", upload_to="images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="picSrc5",
            field=models.ImageField(default="", upload_to="images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="picSrc6",
            field=models.ImageField(default="", upload_to="images"),
            preserve_default=False,
        ),
    ]
