# Generated by Django 4.2.4 on 2023-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0019_alter_slider_picsrc1_alter_slider_picsrc2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slider",
            old_name="description",
            new_name="description1",
        ),
        migrations.RenameField(
            model_name="slider",
            old_name="title",
            new_name="title1",
        ),
        migrations.AddField(
            model_name="slider",
            name="description2",
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="description3",
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="description4",
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="description5",
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="description6",
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="title2",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="title3",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="title4",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="title5",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slider",
            name="title6",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
